version: '3'
services:
  builder:
    build: .
    platform: linux/arm64
    # platform: linux/amd64
    volumes:
      - ./out:/var/task/out:rw
    entrypoint: ["/bin/sh", "-c"]
    command: ["cp dist/*.zip out/"]
